presets:
- labels:
    preset-ci-gce-device-plugin-gpu: "true"
  env:
  - name: KUBE_GCE_NODE_IMAGE
    value: gke-1134-gke-rc5-cos-69-10895-138-0-v190320-pre-nvda-gpu
  - name: KUBE_GCE_NODE_PROJECT
    value: gke-node-images
  - name: NODE_ACCELERATORS
    value: type=nvidia-tesla-k80,count=2

periodics:
- name: ci-kubernetes-e2e-gce-device-plugin-gpu
  cluster: k8s-infra-prow-build
  cron: "30 1-23/2 * * *"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-replacements: "--extract=ci/latest-fast -> --extract=ci/latest-{{.Version}}"
    fork-per-release-cron: 0 0-23/2 * * *, 0 3-23/6 * * *, 0 8-23/12 * * *, 0 8-23/24 * * *
    testgrid-dashboards: sig-release-master-blocking, google-gce
    testgrid-tab-name: gce-device-plugin-gpu-master
    testgrid-alert-email: gke-kubernetes-accelerators-bugs@google.com
    description: "Uses kubetest to run e2e tests (+Feature:GPUDevicePlugin) against a cluster created with cluster/kube-up.sh"
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-stale-results-hours: '24'
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --extract=ci/latest-fast
      - --extract-ci-bucket=k8s-release-dev
      - --env=KUBE_CONTAINER_RUNTIME=docker
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210418-e5f251e-master
      resources:
        limits:
          cpu: 1
          memory: 3Gi
        requests:
          cpu: 1
          memory: 3Gi
- name: ci-kubernetes-e2e-gce-device-plugin-gpu-canary
  cluster: k8s-infra-prow-build
  cron: "30 1-23/2 * * *"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: gce-device-plugin-gpu
    description: Duplicate of ci-kubernetes-e2e-gce-device-plugin-gpu pinned to a k8s-infra project to verify quota
    testgrid-alert-stale-results-hours: '24'
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --extract=ci/latest-fast
      - --extract-ci-bucket=k8s-release-dev
      - --env=KUBE_CONTAINER_RUNTIME=docker
      - --gcp-node-image=gci
      - --gcp-project=k8s-infra-e2e-gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210418-e5f251e-master
      resources:
        limits:
          cpu: 1
          memory: 3Gi
        requests:
          cpu: 1
          memory: 3Gi
