periodics:
- name: ci-aws-ebs-csi-driver-migration-test-latest
  decorate: true
  decoration_config:
    timeout: 1h20m
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-aws-credential-aws-oss-testing: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: aws-ebs-csi-driver
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20210418-e5f251e-master
      command:
      - runner.sh
      args:
      - make
      - test-e2e-migration
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: provider-aws-ebs-csi-driver
    testgrid-tab-name: migration-test-latest
    description: aws ebs csi driver migration test on latest kubernetes
    testgrid-num-columns-recent: '30'
