# For more information on these tests, see
# https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc/hack/prow-run-e2e.sh.
#
# When updating this test, please update the periodics (below) in the same way
# if applicable.
postsubmits:
  kubernetes-sigs/multi-tenancy:
  - name: hnc-postsubmit-test
    annotations:
      testgrid-dashboards: wg-multi-tenancy-hnc
      testgrid-tab-name: postsubmit-tests
      testgrid-alert-email: kubernetes-hnc-dev+alerts@googlegroups.com
    always_run: false
    decorate: true
    decoration_config:
      timeout: 1h
    max_concurrency: 5 # No idea what this should be for HNC
    path_alias: sigs.k8s.io/multi-tenancy
    run_if_changed: "incubator/hnc/.*"
    labels:
      preset-kind-volume-mounts: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20210418-e5f251e-master
        # workdir appears to be the base of the cloned repo
        command: ["wrapper.sh", "incubator/hnc/hack/prow-run-e2e.sh"]
        securityContext:
          privileged: true # Required for docker-in-docker
        resources:
          requests:
            cpu: 1
            memory: "4Gi"

# The periodics are the same as the postsubmits, but we run them occasionally
# to ensure there's no flakiness during periods where there aren't lots of
# submissions. Please keep them as closely in sync as possible.
periodics:
- name: hnc-periodic-test
  annotations:
    testgrid-dashboards: wg-multi-tenancy-hnc
    testgrid-tab-name: periodic-e2e-tests
    testgrid-alert-email: kubernetes-hnc-dev+alerts@googlegroups.com
    testgrid-num-failures-to-alert: "1"
  interval: 24h
  always_run: true # Different from the postsubmit; copied from kind periodics
  decorate: true
  decoration_config:
    timeout: 1h
  labels:
    preset-kind-volume-mounts: "true"
    preset-dind-enabled: "true"
  extra_refs:
    # For periodics, the first repo is the workdir:
    # https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#writing-a-prowjob-that-uses-pod-utilities
  - org: kubernetes-sigs
    repo: multi-tenancy
    base_ref: master
    path_alias: sigs.k8s.io/multi-tenancy
  spec:
    containers:
    - image: gcr.io/k8s-testimages/krte:v20210418-e5f251e-master
      command: ["wrapper.sh", "incubator/hnc/hack/prow-run-e2e.sh"]
      securityContext:
        privileged: true # Required for docker-in-docker
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
